gems:                [jekyll-paginate]
paginate:            5
paginate_path:       'page:num'

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               A Titanic Introduction to R
tagline:             ''
description:         ''
url:                 'http://choens.github.io/titanic'
baseurl:             'http://choens.github.io/titanic'

# About/contact
author:
  name:              Andy Choens
  url:               http://choens.github.io
  email:             andy.choens@gmail.com

# Custom vars
version:             "Spring 2016 (BETA)"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
